services:
    LeTots\WorkflowExtensionBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Tests,Kernel.php}'
        autowire: true
        autoconfigure: true
        public: true
